[global]
   workgroup = PENTESTTV
   server string = Pentest.TV File Server
   security = user
   map to guest = Bad User
   guest account = nobody
   server min protocol = SMB2
   log level = 1

[data]
   comment = Pentest.TV shared data
   path = /srv/share
   browseable = yes
   read only = yes
   guest ok = yes
